---
    name: Checks

    on: [push]

    jobs:
        test-lint:
            name: Test and Lint
            runs-on: ubuntu-24.04
            steps:
                - name: Login to Docker Hub ğŸ”’ğŸ‹
                  uses: docker/login-action@v3
                  with:
                    username: ${{ secrets.DOCKERHUB_USER }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                - name: Checkout ğŸ“
                  uses: actions/checkout@v4
                - name: Test ğŸ§ª
                  run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
                - name: Delete test database âŒ
                  run: |
                    read -p "Do you want to delete the test database? (yes/no): " answer
                    if [ "$answer" = "yes" ]; then
                        echo yes
                    else
                        echo "Test database deletion cancelled."
                    fi
                - name: Lint ğŸ”
                  run: docker compose run --rm app sh -c "flake8"